version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2022
install:
- ps: "Import-Certificate -FilePath \"C:\\projects\\simpleidserver\\certificates\\simpleIdServer.crt\" -CertStoreLocation cert:\\LocalMachine\\Root\nImport-Certificate -FilePath \"C:\\projects\\simpleidserver\\certificates\\simpleIdServer.crt\" -CertStoreLocation cert:\\CurrentUser\\Root \n Install-Module VSSetup -Scope CurrentUser"
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: .\psake.cmd ci
test: off
artifacts:
- path: build\results\*.nupkg
  name: NuGet
- path: build\results\*.zip
  name: Installers
deploy:
- provider: GitHub
  auth_token:
    secure: Czcu42wI76bvJ76aYnPdzYwsgKzV72ojXmOZk0C3jL0H2tnPsGGnffXCQ3EP+700
  artifact: /.*\.zip/
  on:
    branch: master
    appveyor_repo_tag: true
  