# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.14.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  displayName: 'npm install and build'
  inputs:
    targetType: 'inline'
    script: |
      npm install
      npm run build
    workingDirectory: '$(Build.Repository.LocalPath)\website'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    workingDirectory: '$(Build.Repository.LocalPath)\src\IdServer\SimpleIdServer.IdServer.Startup'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    workingDirectory: '$(Build.Repository.LocalPath)\src\IdServer\SimpleIdServer.IdServer.Website.Startup'

- task: CopyFiles@2
  displayName: 'Copy website'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\website\build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\website'

- task: PublishBuildArtifacts@1
  displayName: 'Publish website'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\website'
    ArtifactName: 'website'
    publishLocation: 'Container'